import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Button } from "@chakra-ui/button";
import { Box, Flex } from "@chakra-ui/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const onCLickHandler = () => {
    console.log("hire");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w={"full"} h={"full"} align={"center"} justify={"center"}>
        <Button
          mt={"100px"}
          border={"1px solid red"}
          p={"10px"}
          onClick={() => {
            onCLickHandler();
          }}
        >
          click
        </Button>
      </Flex>
    </>
  );
}
